# Generated by Django 5.2.8 on 2025-11-18 04:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('imageUrl', models.CharField(blank=True, max_length=1024)),
                ('actionUrl', models.CharField(blank=True, max_length=1024)),
                ('displayOrder', models.IntegerField(default=0)),
                ('isActive', models.BooleanField(default=True)),
                ('expiryDate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('levelId', models.AutoField(primary_key=True, serialize=False)),
                ('levelName', models.CharField(max_length=50, unique=True)),
                ('minPoints', models.BigIntegerField()),
                ('pointMultiplier', models.DecimalField(decimal_places=1, max_digits=3)),
                ('themeName', models.CharField(blank=True, max_length=50)),
                ('unlock_Social', models.BooleanField(default=False)),
                ('unlock_Avatar', models.BooleanField(default=False)),
                ('unlock_Games', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reward_Balance_Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('imageUrl', models.CharField(blank=True, max_length=1024)),
                ('balancePrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='VoucherType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('threshold', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('expiryDays', models.IntegerField(default=90)),
                ('costOfGoods', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('stockCount', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('memberId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=50, unique=True)),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('loyaltyPoints', models.BigIntegerField(default=0)),
                ('lifetimePoints', models.BigIntegerField(default=0)),
                ('avatarUrl', models.URLField(blank=True, max_length=1024)),
                ('flair', models.CharField(blank=True, max_length=100)),
                ('socialOptIn', models.BooleanField(default=False)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('balanceExpiryDate', models.DateField(blank=True, null=True)),
                ('preferredLanguage', models.CharField(default='en', max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('level', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.level')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transactionId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('RECHARGE', '代充值'), ('CONSUME_BALANCE', '余额消费 (现场)'), ('CONSUME_CASH', '现金/刷卡 (追踪)'), ('CONSUME_VOUCHER', '核销代金券'), ('REDEEM_MERCH', '余额商城消费'), ('REWARD_ISSUE', '积分兑换'), ('SYSTEM_ADJUST', '系统调整')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discountApplied', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pointsEarned', models.BigIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_transactions', to=settings.AUTH_USER_MODEL)),
                ('relatedProduct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.reward_balance_store')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialLedger',
            fields=[
                ('ledgerId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('REVENUE_BALANCE', '余额收入'), ('REVENUE_STORE', '商城销售收入'), ('COST_OF_GOODS', '商品成本支出'), ('ADJUSTMENT', '财务调整')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('relatedMember', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('relatedTransaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('voucherId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('unused', 'Unused'), ('used', 'Used'), ('expired', 'Expired')], default='unused', max_length=10)),
                ('issueDate', models.DateTimeField(auto_now_add=True)),
                ('expiryDate', models.DateTimeField(blank=True, null=True)),
                ('usedDate', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voucherType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.vouchertype')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='relatedVoucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.voucher'),
        ),
        migrations.CreateModel(
            name='Reward_Points_Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('imageUrl', models.CharField(blank=True, max_length=1024)),
                ('pointsCost', models.BigIntegerField()),
                ('isActive', models.BooleanField(default=True)),
                ('linkedVoucherType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.vouchertype')),
            ],
        ),
        migrations.AddField(
            model_name='reward_balance_store',
            name='linkedVoucherType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.vouchertype'),
        ),
        migrations.CreateModel(
            name='RechargeTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(unique=True)),
                ('grantVoucherCount', models.IntegerField()),
                ('grantVoucherType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.vouchertype')),
            ],
        ),
    ]
