# Generated by Django 5.2.8 on 2025-11-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_announcement_imageurl_announcement_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='content',
            field=models.TextField(blank=True, help_text='如果不填 Action URL，点击横幅将显示此内容'),
        ),
    ]
