# Generated by Django 5.2.8 on 2025-11-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_announcement_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='isTermsAgreed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='termsAgreedTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
