# Generated by Django 5.2.8 on 2025-11-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_member_istermsagreed_member_termsagreedtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('CASHIER', '收银员'), ('STORE_MANAGER', '店长/运营'), ('ACCOUNT_MANAGER', '财务经理'), ('SUPERUSER', '超级管理员')], default='CASHIER', max_length=20),
        ),
    ]
