# Generated by Django 5.2.8 on 2025-11-21 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_member_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.level'),
        ),
    ]
