# Generated by Django 5.2.8 on 2025-11-27 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_member_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='preferredLanguage',
            field=models.CharField(blank=True, default='en', max_length=5, null=True),
        ),
    ]
