# Generated by Django 5.2.8 on 2025-11-27 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_member_preferredlanguage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('MEMBER', '普通会员'), ('CASHIER', '收银员'), ('STORE_MANAGER', '店长/运营'), ('ACCOUNT_MANAGER', '财务经理'), ('SUPERUSER', '超级管理员')], default='MEMBER', max_length=20),
        ),
    ]
