# Generated by Django 5.2.8 on 2025-11-30 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_member_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='levelExpiryDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
