"""
Django settings for lluvia_backend project.
Generated by 'django-admin startproject' using Django 5.2.8.
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# (这是 Django 自动生成的，如果你的还在，请用你原来的。如果不在了，这个新的也可以用)
SECRET_KEY = 'django-insecure-@e%y7k_3q+8!z@b(b$p^q@m&f!j5(w*#_d&9v-8c(v+q_x#i_x'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition
# --- 这是我们 V15 蓝图的修改 (步骤 11) ---
INSTALLED_APPS = [
    'api.apps.ApiConfig', # 🚩 我们的 V15 "api" 应用
    # DRF 框架 (步骤 25)
    'rest_framework',
    'rest_framework.authtoken',
    'drf_spectacular',
    # ---------------------
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]
# ----------------------------------------

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'lluvia_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lluvia_backend.wsgi.application'


# Database
# --- 这是我们 V15 蓝图的修改 (步骤 7) ---
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql', # 使用 PostgreSQL
        'NAME': 'lluvia_db',                      # 数据库名称 (来自步骤 4)
        'USER': 'postgres',                       # 默认的超级用户名
        'PASSWORD': 'LV145@telokayer',         # 🚩 在这里输入你的密码！
        'HOST': 'localhost',                      # 我们的服务器在本地
        'PORT': '5432',                           # 默认端口 (来自步骤 3)
    }
}
# ----------------------------------------


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us' # V7 蓝图: 默认英文

TIME_ZONE = 'Asia/Singapore'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# --- 这是我们 V15 蓝图的修改 (步骤 11) ---
# V7 蓝图: 告诉 Django 使用我们的自定义 Member 表
AUTH_USER_MODEL = 'api.Member' 
# V15 蓝图: Django Rest Framework (DRF) 的设置

# 告诉 DRF 我们希望它如何工作
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema', # 自动 API 文档

    # 🚩 激活 Token 认证！
    # (现在，所有 API 默认都需要 Token 才能访问)
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],

    # 🚩 (但我们稍后会为 'login' 和 'register' 开放例外)
}

# 告诉 "drf_spectacular" (文档工具) 关于我们的项目
SPECTACULAR_SETTINGS = {
    'TITLE': 'LLUVIA Bar API',
    'DESCRIPTION': 'LLUVIA V15 会员系统的完整 API 蓝图',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}
# ----------------------------------------

# V15 蓝图: CORS (跨域) 设置
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",     # Admin Portal
    "http://127.0.0.1:3000",
    "http://localhost:3001",     # 🚩 Member Portal (新)
    "http://127.0.0.1:3001",     
]


# 🚩 V8 蓝图: 文件存储配置 (Media Settings) 必须在 CORS 列表的外面！
import os

MEDIA_URL = '/media/'
# 在项目根目录创建 media 文件夹
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'

# ... (settings.py 的其他内容) ...

# ==============================================
# 📧 邮件服务配置 (Gmail SMTP)
# ==============================================

# 1. 使用 SMTP 后端
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# 2. Gmail 服务器地址
EMAIL_HOST = 'smtp.gmail.com'

# 3. 端口 (TLS 通常用 587)
EMAIL_PORT = 587

# 4. 开启安全连接
EMAIL_USE_TLS = True

# 5. 你的 Gmail 账号 (发送方)
# 🚩 请修改：填入你刚才登录 Google 的那个邮箱地址
EMAIL_HOST_USER = 'lluviamembers@gmail.com'

# 6. 你的应用专用密码 (钥匙)
# 🚩 请修改：填入你刚刚生成的那个 16 位密码
# (可以直接粘贴，带不带空格都没关系，放在引号里就行)
EMAIL_HOST_PASSWORD = 'wuuq ypni xyzs pwxt'

# 7. 默认发件人 (用户收到邮件时显示的名字)
DEFAULT_FROM_EMAIL = 'LLUVIA System <lluviamembers@gmail.com>'