"""
Django settings for lluvia_backend project.
Generated by 'django-admin startproject' using Django 5.2.8.
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# (这是 Django 自动生成的，如果你的还在，请用你原来的。如果不在了，这个新的也可以用)
SECRET_KEY = 'django-insecure-@e%y7k_3q+8!z@b(b$p^q@m&f!j5(w*#_d&9v-8c(v+q_x#i_x'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['206.189.157.1', 'localhost', '127.0.0.1', '.lluvia.app']

CSRF_TRUSTED_ORIGINS = [
    'https://lluvia.app',
    'https://www.lluvia.app',
]

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Application definition
# --- 这是我们 V15 蓝图的修改 (步骤 11) ---
INSTALLED_APPS = [
    'api.apps.ApiConfig', # 🚩 我们的 V15 "api" 应用
    # DRF 框架 (步骤 25)
    'rest_framework',
    'rest_framework.authtoken',
    'drf_spectacular',
    # ---------------------
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]
# ----------------------------------------

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'lluvia_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lluvia_backend.wsgi.application'


# Database
# --- 这是我们 V15 蓝图的修改 (步骤 7) ---
# 找到 DATABASES 部分，替换为：
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'lluvia_db',
        
        # 🚩 必须改！服务器上的用户名是 lluvia_user (不是 postgres)
        'USER': 'lluvia_user',
        
        # 🚩 必须改！服务器上的密码是你刚才设的强密码 (不是本地那个)
        'PASSWORD': 'Final2025!', 
        
        'HOST': 'localhost',
        'PORT': '5432',
    }
}
# ----------------------------------------


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us' # V7 蓝图: 默认英文

TIME_ZONE = 'Asia/Singapore'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'django_static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# --- 这是我们 V15 蓝图的修改 (步骤 11) ---
# V7 蓝图: 告诉 Django 使用我们的自定义 Member 表
AUTH_USER_MODEL = 'api.Member' 
# V15 蓝图: Django Rest Framework (DRF) 的设置

# 告诉 DRF 我们希望它如何工作
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema', # 自动 API 文档

    # 🚩 激活 Token 认证！
    # (现在，所有 API 默认都需要 Token 才能访问)
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],

    # 🚩 (但我们稍后会为 'login' 和 'register' 开放例外)
}

# 告诉 "drf_spectacular" (文档工具) 关于我们的项目
SPECTACULAR_SETTINGS = {
    'TITLE': 'LLUVIA Bar API',
    'DESCRIPTION': 'LLUVIA V15 会员系统的完整 API 蓝图',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}
# ----------------------------------------

# V15 蓝图: CORS (跨域) 设置
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",     # Admin Portal
    "http://127.0.0.1:3000",
    "http://localhost:3001",     # 🚩 Member Portal (新)
    "http://127.0.0.1:3001",     
]


# 🚩 V8 蓝图: 文件存储配置 (Media Settings) 必须在 CORS 列表的外面！
import os

MEDIA_URL = '/media/'
# 在项目根目录创建 media 文件夹
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'

# ... (settings.py 的其他内容) ...

# ==============================================
# 📧 邮件服务配置 (SendGrid - 生产环境版)
# ==============================================

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.sendgrid.net'  # SendGrid 的服务器地址

# 🚩 核心关键：DigitalOcean 封锁了 587，必须用 2525！
EMAIL_PORT = 2525                 

EMAIL_USE_TLS = True

# 🚩 用户名固定填 'apikey' (这是 SendGrid 的规定，不要填你的邮箱！)
EMAIL_HOST_USER = 'apikey'

# 🚩 密码填你刚才拿到的那一长串 Key
EMAIL_HOST_PASSWORD = 'PUT_YOUR_SENDGRID_KEY_ON_SERVER'

# 🚩 发件人必须是你刚才在 SendGrid 验证过的那个 Gmail
DEFAULT_FROM_EMAIL = 'LLUVIA System <lluviamembers@gmail.com>'